### PR TITLE
Import Employees & Location & Transactions Component

### PR DESCRIPTION
**Pull request by laurenesco**
Changes are as follows:
- Added employee_search_form, employee_add_form, employee_edit_form
- Standardized control names to conform to agreed convention
- Resized the forms to match the standardized form size
- Enabled the navigation controls between the main menu, employee search form, employee add form, employee edit form

### CODE REVIEW

**Comment by laurenesco** [comment]
Imported Location Component:

- Added a cancel button to employee_search_form
- Added the location form
    - This one form will handle all CRUD operations for now
    - The edit and delete button are concealed until a location is selected
    - An "AddMode" was implemented to handle the transitioning from adding to not adding a location
    - This mode can be used as a template for an EditMode in the future
    - Pressing the add button will toggle the form to add mode, pressing the same button again will submit while 
      pressing cancel in add mode will cancel the add operation. Pressing the cancel button outside of add mode 
      will return the user to the main menu
- The location form was connected to the main menu, which necessitated adding a new button the navigation bar

**Comment by laurenesco** [comment]
Changes:
- Added Transactions form. Since transactions cannot be edited (they are supposed to be auto-generated upon a reservation payment), this form does not have an add or edit functionality.
- Navigation should be functional between all forms.
- Added a method to Main Menu form which resets the form, so when you press "Cancel" from any other page, it sends you back to the home page.
- Removed the main_menu_Load function from the Main Menu form, as it was not being referenced anywhere and it's only use was to title the window "Main Menu", which it was already titled elsewhere without the function.

**Comment by laurenesco** [comment]
Changes:
- Added the Location Add and Location Edit form. I figured we wanted to get away from the messy spaghetti User Controls being used for a million different purposes, so I went ahead and added these. This will help modularization and maintainability.
- Made some cosmetic changes for consistency
- Did some resource management with disposing of resources when leaving a user control

**Review by eliseomrico — APPROVED** [review]
I have reviewed these changes. Approving PR.

**Pull request merged**
